import streamlit as st
import geopandas as gpd
import folium
from streamlit_folium import st_folium

st.set_page_config(
    page_title="Bali Environmental Suitability",
    layout="wide"
)

# --------------------
# Load data
# --------------------
solar = gpd.read_file("data/solar.shp")
wind = gpd.read_file("data/wind.shp")
protected = gpd.read_file("data/protected.shp")

# --------------------
# Helper function
# --------------------
def make_map(layer, name, color, show_protected=True):
    m = folium.Map(
        location=[-8.4, 115.2],
        zoom_start=9,
        tiles="CartoDB positron"
    )

    if show_protected:
        folium.GeoJson(
            protected,
            name="Protected Areas",
            style_function=lambda x: {
                "color": "red",
                "fillColor": "red",
                "weight": 1,
                "fillOpacity": 0.20,
            },
        ).add_to(m)

    folium.GeoJson(
        layer,
        name=name,
        style_function=lambda x: {
            "color": color,
            "fillColor": color,
            "weight": 1,
            "fillOpacity": 0.50,
        },
    ).add_to(m)

    folium.LayerControl(collapsed=False).add_to(m)
    return m


# --------------------
# Header
# --------------------
st.title("🌿 Bali Environmental Suitability for Solar PV and Onshore Wind")

st.markdown("""
This dashboard presents an **environmental suitability analysis** for renewable energy planning in Bali, Indonesia.

The analysis focuses on **environmental constraints and terrain filtering**.  
Technical factors such as grid access, road proximity, wind resource quality, and solar irradiance are not included.
""")

st.divider()

# --------------------
# Metrics
# --------------------
col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Solar PV", "Slope ≤ 5°")

with col2:
    st.metric("Onshore Wind", "Slope ≤ 15°")

with col3:
    st.metric("Main Focus", "Environmental Screening")

st.divider()

# --------------------
# Tabs
# --------------------
tab1, tab2, tab3, tab4 = st.tabs(
    ["☀️ Solar PV", "💨 Onshore Wind", "🛡️ Protected Areas", "📌 Methodology"]
)

with tab1:
    st.header("☀️ Solar PV Suitable Areas")
    st.markdown("""
    Suitable solar PV areas were identified after excluding sensitive environmental zones and applying a strict slope threshold.

    **Included constraints:**
    - Protected areas excluded
    - Temple buffer zones excluded
    - River buffer zones excluded
    - Coastal buffer zones excluded
    - Slope limited to **≤ 5°**
    """)
    st_folium(
        make_map(solar, "Solar PV Suitable Areas", "orange"),
        width=1250,
        height=620
    )

with tab2:
    st.header("💨 Onshore Wind Suitable Areas")
    st.markdown("""
    Suitable onshore wind areas were identified using the same environmental exclusion layers, with a more flexible terrain threshold.

    **Included constraints:**
    - Protected areas excluded
    - Temple buffer zones excluded
    - River buffer zones excluded
    - Coastal buffer zones excluded
    - Slope limited to **≤ 15°**
    """)
    st_folium(
        make_map(wind, "Onshore Wind Suitable Areas", "blue"),
        width=1250,
        height=620
    )

with tab3:
    st.header("🛡️ Environmental Protection Context")
    st.markdown("""
    Protected areas were used as exclusion zones in the environmental screening process.
    These areas are shown here as context for understanding why some regions were removed from the final suitability layers.
    """)
    st_folium(
        make_map(protected, "Protected Areas", "red", show_protected=False),
        width=1250,
        height=620
    )

with tab4:
    st.header("📌 Methodology")
    st.markdown("""
    ### 1. Base Land Preparation
    Land-cover suitable polygons were used as the starting layer for the analysis.

    ### 2. Environmental Exclusion
    Sensitive areas were removed, including:
    - Protected areas
    - Temple buffer zones
    - River buffer zones
    - Coastal buffer zones

    ### 3. Terrain Filtering
    Slope thresholds were applied separately:
    - **Solar PV:** ≤ 5°
    - **Onshore Wind:** ≤ 15°

    ### 4. Final Outputs
    Final suitable areas were generated by intersecting the environmentally allowed land with the slope-suitable zones.

    ### Limitation
    This is an **environmental and terrain suitability analysis only**.  
    It does not include grid proximity, roads, resource potential, land ownership, or economic feasibility.
    """)

st.divider()

st.caption(
    "Developed using ArcGIS Pro, Python, GeoPandas, Folium, and Streamlit."
)